apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
        ports:
        - containerPort: 80
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: manageddisk
